# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  allowlist_external_dirs:
    - /config/python
    - /config

climate:
  - platform: generic_thermostat
    name: Ucebna
    heater: switch.ucebna_heater
    target_sensor: sensor.ucebna

input_number:
  tempidle:
    name: TeplotaIdle
    initial: 19
    min: 10
    max: 30
    step: 1
  tempactive:
    name: TeplotaActive
    initial: 22
    min: 10
    max: 30
    step: 1

input_text:
  username:
    name: Uzivatelske jmeno
    initial: itxxxx@sspu-opava.cz
  password:
    name: Heslo
    mode: password

notify:
  - platform: file
    name: filenotify
    filename: /config/python/file.csv

sensor:
  - platform: file
    name: temperature
    file_path: /config/python/ofile.csv
    value_template: "{{ value_json.temperature }}"
    unit_of_measurement: "°C"
  - platform: file
    name: ucebna
    file_path: /config/test.csv
    value_template: "{{ value_json.temperature }}"
    unit_of_measurement: "°C"

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
